# Generated by Django 2.2 on 2021-03-23 13:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210323_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='商品详情'),
        ),
    ]
